//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCC.Core.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCC.Core.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;name&quot;:&quot;MSBuild Log&quot;,&quot;title&quot;:&quot;0 errors - 1 warning&quot;,&quot;summary&quot;:&quot;- [TestConsoleApp1/Program.cs(13)](https://github.com/justaprogrammer/TestConsoleApp1/tree/815aa7a3051cc0d0ae6c6c2c89cba125e8027d86/TestConsoleApp1/Program.cs#L13) **Warning - CS0219** The variable &apos;hello&apos; is assigned but its value is never used\r\n&quot;,&quot;text&quot;:null,&quot;conclusion&quot;:&quot;success&quot;,&quot;annotations&quot;:[{&quot;filename&quot;:&quot;TestConsoleApp1/Program.cs&quot;,&quot;annotationLevel&quot;:&quot;warning&quot;,&quot;title&quot;:&quot;CS0219: TestConsoleApp1/Program.cs(13)&quot;,&quot;rawDetails&quot;:null,&quot;message&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CheckRunSample {
            get {
                return ResourceManager.GetString("CheckRunSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Name&quot;:&quot;MSBuild Log&quot;,&quot;Title&quot;:&quot;0 errors - 1 warning&quot;,&quot;Summary&quot;:&quot;- [TestConsoleApp1/Program.cs(13)](https://github.com/justaprogrammer/TestConsoleApp1/tree/815aa7a3051cc0d0ae6c6c2c89cba125e8027d86/TestConsoleApp1/Program.cs#L13) **Warning - CS0219** The variable &apos;hello&apos; is assigned but its value is never used\r\n&quot;,&quot;Text&quot;:null,&quot;Conclusion&quot;:0,&quot;Annotations&quot;:[{&quot;Filename&quot;:&quot;TestConsoleApp1/Program.cs&quot;,&quot;AnnotationLevel&quot;:1,&quot;Title&quot;:&quot;CS0219: TestConsoleApp1/Program.cs(13)&quot;,&quot;RawDetails&quot;:null,&quot;Message&quot;:&quot;The variable &apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CheckRunSampleOriginal {
            get {
                return ResourceManager.GetString("CheckRunSampleOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;names&quot;:&quot;MSBuild Log&quot;,&quot;titles&quot;:&quot;0 errors - 1 warning&quot;,&quot;summarys&quot;:&quot;- [TestConsoleApp1/Program.cs(13)](https://github.com/justaprogrammer/TestConsoleApp1/tree/815aa7a3051cc0d0ae6c6c2c89cba125e8027d86/TestConsoleApp1/Program.cs#L13) **Warning - CS0219** The variable &apos;hello&apos; is assigned but its value is never used\r\n&quot;,&quot;text&quot;:null,&quot;conclusion&quot;:&quot;success&quot;,&quot;annotations&quot;:[{&quot;filename&quot;:&quot;TestConsoleApp1/Program.cs&quot;,&quot;annotationLevel&quot;:&quot;warning&quot;,&quot;title&quot;:&quot;CS0219: TestConsoleApp1/Program.cs(13)&quot;,&quot;rawDetails&quot;:null,&quot;messa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CheckRunSampleWrong {
            get {
                return ResourceManager.GetString("CheckRunSampleWrong", resourceCulture);
            }
        }
    }
}
